package com.tobiasheymann.ep.view.theme

import androidx.compose.ui.graphics.Color

val BACKGROUND = Color(0xFFF9F9F9)
val SURFACE = Color(0xFFFFFFFF)
val PRIMARY = Color(0xFF7A9972)
val PRIMARY_VARIABLE = Color(0xFF7A9972)
val SECONDARY = Color(0xFFDCE5DA)
val SECONDARY_VARIABLE = Color(0xFFDCE5DA)
val TEXT_PRIMARY = Color(0xFF333333)
val TEXT_SECONDARY = Color(0xFFC0C0C0)

val DARK_BACKGROUND = Color(0xFF121212)
val DARK_SURFACE = Color(0xFF1E1E1E)
val DARK_PRIMARY = Color(0xFF7A9972)
val DARK_PRIMARY_VARIABLE = Color(0xFFDCE5DA)
val DARK_SECONDARY = Color(0xFF7A9972)
val DARK_SECONDARY_VARIABLE = Color(0xFFDCE5DA)
val DARK_TEXT_PRIMARY = Color(0xFFF0F0F0)
val DARK_TEXT_SECONDARY = Color(0xFFC0C0C0)